version: '3'

services:
  php:
    container_name: console_php
    build: ./docker/php
    volumes:
      - ./app:/var/www/html
    working_dir: /var/www/html
    command: tail -f /dev/null

  db_console:
    image: mysql:8.4
    container_name: db_console
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql_data: